### test get movie by eidr
POST http://localhost:8080/api/movie/get-movies-table
Content-Type: application/json

{
    "eidrCode": null,
    "name": null,
    "page": 1,
    "pageSize": 100,
    "orderBy": "NAME",
    "direction": "ASC"
}